<a href="https://colab.research.google.com/github/matheuschrys/Calculadora-Algebrica-em-python.Somente-Codigo/blob/main/trabalho_de_algebra_linear_chrys.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ***Vetores com Numpy***

**Soma de Vetores:**

In [ ]:
from IPython.core.display import clear_output
import numpy as np
np.set_printoptions(precision=3, suppress=True)

m = int(input("Digite quantos vetores você quer: "))
n = int(input("Digite o tamanho dos vetores: "))

todos_vetores = np.zeros((m, n))

print("Digite os vetores: ")
for i in range(m):
  for j in range(n):
    todos_vetores[i, j] = float(input(f"Vetor {i+1}, Posição {j+1}: "))

soma_vet = np.sum(todos_vetores, axis=0)

clear_output()

print(f"Você usou {m} vetores de tamanho {n}.")
for i, vetor in enumerate(todos_vetores):
  print(f"O vetor {i+1} é: {vetor}")
print(f"A soma dos vetores é: {soma_vet}")

Você usou 2 vetores de tamanho 2.
O vetor 1 é: [5. 5.]
O vetor 2 é: [5. 5.]
A soma dos vetores é: [10. 10.]


**Subtração de Vetores:**

In [ ]:
from IPython.core.display import clear_output
import numpy as np

m = int(input("Digite quantos vetores você quer: "))
n = int(input("Digite o tamanho dos vetores: "))

todos_vetores = np.zeros((m, n))

print("Digite os vetores: ")
for i in range(m):
  for j in range(n):
    todos_vetores[i, j] = float(input(f"Vetor {i+1}, Posição {j+1}: "))

if m > 0:
    sub_vet = todos_vetores[0]
    for i in range(1, m):
        sub_vet = sub_vet - todos_vetores[i]
else:
    sub_vet = np.array([])

clear_output()

print(f"Você usou {m} vetores de tamanho {n}.")
for i, vetor in enumerate(todos_vetores):
  print(f"O vetor {i+1} é: {vetor}")
print(f"A subtração dos vetores é: {sub_vet}")

Você usou 3 vetores de tamanho 2.
O vetor 1 é: [10. 10.]
O vetor 2 é: [2. 2.]
O vetor 3 é: [1. 1.]
A subtração dos vetores é: [7. 7.]


**Produto Interno de Vetores:**

In [ ]:
m = int(input("Digite quantos vetores você quer: "))
n = int(input("Digite o tamanho dos vetores: "))

todos_vetores = np.zeros((m, n))

print("Digite os vetores: ")
for i in range(m):
  for j in range(n):
    todos_vetores[i, j] = float(input(f"Vetor {i+1}, Posição {j+1}: "))

prod_vet = np.prod(todos_vetores, axis=0)

clear_output()

print(f"Você usou {m} vetores de tamanho {n}.")
for i, vetor in enumerate(todos_vetores):
  print(f"O vetor {i+1} é: {vetor}")
print(f"O produto interno dos vetores é: {prod_vet}")

Você usou 3 vetores de tamanho 2.
O vetor 1 é: [5. 5.]
O vetor 2 é: [5. 5.]
O vetor 3 é: [5. 5.]
O produto interno dos vetores é: [125. 125.]


**Norma do Vetor:**

In [ ]:
n = int(input("Digite o tamanho do vetor: "))

va_np = np.zeros(n)

print("Vetor:")
for i in range(n):
   va_np[i] = float(input(f"Digite o {i+1}º número do vetor A: "))

norma = np.linalg.norm(va_np)

clear_output()

print(f"O Vetor é: {va_np}")
print(f"A norma dele é: {norma}")

O Vetor é: [25. 10.]
A norma dele é: 26.92582403567252


**Distância Euclidiana:**

In [ ]:
m = int(input("Digite quantos vetores você quer: "))
n = int(input("Digite o tamanho dos vetores: "))

todos_vetores = np.zeros((m, n))

print("Digite os vetores: ")
for i in range(m):
  for j in range(n):
    todos_vetores[i, j] = float(input(f"Vetor {i+1}, Posição {j+1}: "))

norma_in = np.linalg.norm(todos_vetores, axis=1)

clear_output()

print(f"Você usou {m} vetores de tamanho {n}.")
print(todos_vetores)
print(f"As normas de cada vetor são: {norma_in}!")

Você usou 3 vetores de tamanho 5.
[[5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]]
As normas de cada vetor são: [11.18 11.18 11.18]!


### ***Vetores sem Numpy***

**Soma de vetores:**

In [ ]:
def criar_vetor(tamanho, nome_vetor):
    vetor = []
    print(f"\n Preenchendo o {nome_vetor} (tamanho {tamanho}) ")

    for i in range(tamanho):
        while True:
            try:
                num_texto = input(f"  Digite o elemento {i + 1}: ")
                num_float = float(num_texto)

                vetor.append(num_float)
                break
            except ValueError:
                print("  Erro: Isso não é um número válido. Tente novamente.")
    return vetor

def soma_vetores_sem_numpy(v1, v2):
    return [x + y for (x, y) in zip(v1, v2)]

print("Soma de Vetores")
tamanho_vetor = 0
while tamanho_vetor <= 0:
    try:
        texto_tamanho = input("Qual será a dimensão (tamanho) dos vetores? ")
        tamanho_vetor = int(texto_tamanho)
        if tamanho_vetor <= 0:
            print("O tamanho deve ser um número positivo.")
    except ValueError:
        print("Erro: Digite um número inteiro válido.")
vetor1 = criar_vetor(tamanho_vetor, "Vetor 1")
vetor2 = criar_vetor(tamanho_vetor, "Vetor 2")

vetor_soma = soma_vetores_sem_numpy(vetor1, vetor2)

print("\nResultado Final")
print(f"Vetor 1: {vetor1}")
print(f"Vetor 2: {vetor2}")
print(f"Soma:    {vetor_soma}")

**Subtração de vetores:**

In [ ]:
def criar_vetor(tamanho, nome_vetor):
    vetor = []
    print(f"\n Preenchendo o {nome_vetor} (tamanho {tamanho}) ")

    for i in range(tamanho):
        while True:
            try:
                num_texto = input(f"  Digite o elemento {i + 1}: ")
                num_float = float(num_texto)

                vetor.append(num_float)
                break
            except ValueError:
                print("Erro: Isso não é um número válido. Tente novamente.")
    return vetor

def subtração_vetores_sem_numpy(v1, v2):
    return [x - y for (x, y) in zip(v1, v2)]

print("Subtração de Vetores")
tamanho_vetor = 0
while tamanho_vetor <= 0:
    try:
        texto_tamanho = input("Qual será a dimensão (tamanho) dos vetores? ")
        tamanho_vetor = int(texto_tamanho)
        if tamanho_vetor <= 0:
            print("O tamanho deve ser um número positivo.")
    except ValueError:
        print("Erro: Digite um número inteiro válido.")
vetor1 = criar_vetor(tamanho_vetor, "Vetor 1")
vetor2 = criar_vetor(tamanho_vetor, "Vetor 2")

vetor_sub = subtração_vetores_sem_numpy(vetor1, vetor2)

print("\nResultado Final")
print(f"Vetor 1: {vetor1}")
print(f"Vetor 2: {vetor2}")
print(f"Subtração:   {vetor_sub}")

**Produto Interno:**

In [ ]:
def pedir_tamanho_vetor():
    tamanho = 0
    while tamanho <= 0:
        try:
            texto_tamanho = input("Qual será a dimensão (tamanho) dos vetores? ")
            tamanho = int(texto_tamanho)
            if tamanho <= 0:
                print("O tamanho deve ser um número inteiro positivo.")
        except ValueError:
            print("Erro: Digite um número inteiro válido.\n")
    return tamanho

def criar_vetor(tamanho, nome_vetor):
    vetor = []
    print(f"\n--- Preenchendo o {nome_vetor} (tamanho {tamanho}) ---")

    for i in range(tamanho):
        while True:
            try:
                num_texto = input(f"  Digite o elemento {i + 1}: ")
                num_float = float(num_texto)
                vetor.append(num_float)
                break
            except ValueError:
                print("  Erro: Isso não é um número válido. Tente novamente.")
    return vetor

def produto_interno(v1, v2):
    soma_total = 0
    for i in range(len(v1)):
        soma_total += v1[i] * v2[i]
    return soma_total

print("Produto Interno (Escalar)")
tamanho = pedir_tamanho_vetor()
vetor1 = criar_vetor(tamanho, "Vetor 1")
vetor2 = criar_vetor(tamanho, "Vetor 2")

resultado = produto_interno(vetor1, vetor2)

print("\n Resultado")
print(f"Vetor 1: {vetor1}")
print(f"Vetor 2: {vetor2}")
print(f"Produto Interno (v1 · v2): {resultado}")

**Norma:**

In [ ]:
def pedir_tamanho_vetor():
    tamanho = 0
    while tamanho <= 0:
        try:
            texto_tamanho = input("Qual será a dimensão (tamanho) do vetor? ")
            tamanho = int(texto_tamanho)
            if tamanho <= 0:
                print("O tamanho deve ser um número inteiro positivo.")
        except ValueError:
            print("Erro: Digite um número inteiro válido.\n")
    return tamanho

def criar_vetor(tamanho, nome_vetor):
    vetor = []
    print(f"\n Preenchendo o {nome_vetor} (tamanho {tamanho}) ")

    for i in range(tamanho):
        while True:
            try:
                num_texto = input(f"  Digite o elemento {i + 1}: ")
                num_float = float(num_texto)
                vetor.append(num_float)
                break
            except ValueError:
                print("  Erro: Isso não é um número válido. Tente novamente.")
    return vetor

def norma(v):
    soma_dos_quadrados = 0
    for x in v:
        soma_dos_quadrados += x**2

    norma = soma_dos_quadrados ** 0.5
    return norma

print(" Norma(Comprimento)")
tamanho = pedir_tamanho_vetor()
vetor = criar_vetor(tamanho, "Vetor")

resultado = norma(vetor)

print("\n--- Resultado ---")
print(f"Vetor: {vetor}")
print(f"Norma (||v||): {resultado}")

**Distância Euclidiana:**

In [ ]:
def pedir_tamanho_vetor():
    tamanho = 0
    while tamanho <= 0:
        try:
            texto_tamanho = input("Qual será a dimensão (tamanho) dos vetores? ")
            tamanho = int(texto_tamanho)
            if tamanho <= 0:
                print("O tamanho deve ser um número inteiro positivo.")
        except ValueError:
            print("Erro: Digite um número inteiro válido.\n")
    return tamanho

def criar_vetor(tamanho, nome_vetor):
    vetor = []
    print(f"\nPreenchendo o {nome_vetor} (tamanho {tamanho})")

    for i in range(tamanho):
        while True:
            try:
                num_texto = input(f"  Digite o elemento {i + 1}: ")
                num_float = float(num_texto)
                vetor.append(num_float)
                break
            except ValueError:
                print(" Erro: Isso não é um número válido. Tente novamente.")
    return vetor



def distancia_euclidiana(v1, v2):
    soma_diferencas_quadradas = 0
    for i in range(len(v1)):
        diferenca = v1[i] - v2[i]
        soma_diferencas_quadradas += diferenca ** 2

    distancia = soma_diferencas_quadradas ** 0.5
    return distancia

print("Distância Euclidiana")

tamanho = pedir_tamanho_vetor()
vetor1 = criar_vetor(tamanho, "Vetor 1 (Ponto A)")
vetor2 = criar_vetor(tamanho, "Vetor 2 (Ponto B)")

resultado = distancia_euclidiana(vetor1, vetor2)

print("\nResultado:")
print(f"Vetor 1: {vetor1}")
print(f"Vetor 2: {vetor2}")
print(f"Distância Euclidiana: {resultado}")

### ***Autovalor e Autovetor comNP***

In [ ]:
A = int(input("Digite o tamanho da matriz: "))

matriz = np.zeros((A, A))

print("Digite os elementos da matriz: ")
for i in range(A):
  for j in range(A):
    matriz[i, j] = float(input(f"Elemento {i+1}, {j+1}: "))

autovalores, autovetores = np.linalg.eig(matriz)

clear_output()

print(f"A matriz é: \n{matriz}")
print(f"Os autovalores são: \n{autovalores}")
print(f"Os autovetores são: \n{autovetores}")

### ***Autovalor e Autovetor semNP***

In [ ]:
import math

def dot_product(v1, v2):
    if len(v1) != len(v2):
        raise ValueError("Os Vetores devem possuir o mesmo tamanho")
    return sum(x * y for x, y in zip(v1, v2))

def matrix_vector_mult(A, v):
    if len(A[0]) != len(v):
        raise ValueError("As dimensões são incompatíveis para multiplicar")

    result = []
    for row in A:
        result.append(dot_product(row, v))
    return result

def vector_norm(v):
    return math.sqrt(dot_product(v, v))

def normalize_vector(v):
    norm = vector_norm(v)
    if norm == 0:
        return v
    return [x / norm for x in v]


def power_iteration(A, max_iter=100, tolerance=1e-6):
    n = len(A)
    if n == 0 or len(A[0]) != n:
        raise ValueError("A matriz deve ser quadrada")

    v = [1.0] * n
    v = normalize_vector(v)

    eigenvalue = 0.0

    for _ in range(max_iter):
        old_eigenvalue = eigenvalue

        Av = matrix_vector_mult(A, v)

        v = normalize_vector(Av)

        eigenvalue = dot_product(v, Av)

        if abs(eigenvalue - old_eigenvalue) < tolerance:
            break

    return eigenvalue, v

A = [
    [4, 1, 1],
    [1, 3, -1],
    [1, -1, 2]
]

autovalor_dom, autovetor_dom = power_iteration(A)

print("-----Método da Potência-----")
print(f"Matriz A")
for row in A:
    print(row)

print("\nO valor do AutoValor:")
print(round(autovalor_dom, 6))

print("\nO valor do AutoVetor:")
print([round(x, 6) for x in autovetor_dom])

print("\n-----Verificação-----")
Av = matrix_vector_mult(A, autovetor_dom)
lambda_v = [autovalor_dom * x for x in autovetor_dom]

print("A * v     =", [round(x, 4) for x in Av])
print("lambda * v =", [round(x, 4) for x in lambda_v])
